### ISSUE TITLE
Provide mechanism for geospatial searching of resources?

### ISSUE THREAD

**Issue by MathewBiddle** [chiaweh2/CEFI-info-hub-list#28]
I was thinking about the information we were collecting and started wondering how we might be able to facilitate geospatial searching through the resources. Currently we have a list of regions. 

https://github.com/chiaweh2/CEFI-info-hub-list/blob/a1898e0aa2d45437490653d20288d83f5673b256/data/cefi_list.json#L180-L203

I have a couple ideas on the topic.

1. Adjust the regions in this list to align with a standard definition and polygon collection (eg. https://www.marineregions.org/sources.php, shapefiles available at https://www.marineregions.org/downloads.php - we could provide those on a map in this repo as they have [OGC services](https://www.marineregions.org/webservices.php))
2. Allow the user to submit a custom polygon in [WKT](https://www.vertica.com/docs/9.3.x/HTML/Content/Authoring/AnalyzingData/Geospatial/Spatial_Definitions/WellknownTextWKT.htm#:~:text=Well%2DKnown%20Text%20(WKT)%20is%20an%20ASCII%20representation%20of,WKT%20Example) or as [geoJSON](https://geojson.org/) in the region field 
```
- type: textarea
  id: cregions
  attributes:
    label: Regions
    description: Add region polygon as WKT or geoJSON here.
    placeholder: {"type": "Feature","geometry": {"type": "Point","coordinates": [125.6, 10.1]},"properties": {"name": "Dinagat Islands"}}
  validations:
    required: true
  validations:
    required: true
```
