### ISSUE TITLE
Create GitHub issue template

### ISSUE THREAD

**Issue by MathewBiddle** [chiaweh2/CEFI-info-hub-list#3]
See this for details: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

**Comment by MathewBiddle** [comment]
Some examples at https://github.com/MathewBiddle/CEFI-info-hub-list/tree/main/.github/ISSUE_TEMPLATE

**Comment by MathewBiddle** [comment]
Now that we have the definitions available, we can write a simple python script to parse that json file, pull out the definitions, and write them to dropdown menus in an issue template. For example,
```
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
```
https://github.com/chiaweh2/CEFI-info-hub-list/blob/ec8a4e2d41f1f32f5bfdaea0afa5ba1399191648/data/cefi_list.json#L4-L232

I'll tinker around in my fork and send a note once it's ready to have a look.
